"""F3.5 (MI-20): generates seed/sample_files/*.csv and *.xlsx -- the files
imported *live* during the demo (import -> evaluation -> alert, in real
time, not data already seen in the 90-day history).

Deliberately standalone: unlike seed/generators/*, this script needs no
database connection. It reuses seed/generators/catalog.py's constants
(FAMILIES, CHARACTERISTIC_TYPES, TOLERANCE_RANGES) so column names and part
codes line up with whatever a real `python -m seed` run seeds, without
requiring one to exist first -- these files must be regenerable by anyone
prepping a demo laptop with no backend running yet.

Column format: identifying columns (part_number, batch_lot, run_at,
machine_code, operator_identifier, sample_sequence) plus one COL_<balloon>
column per characteristic, matching MeasurementProgram.output_mapping's
{balloon_number: "COL_<balloon_number>"} scheme (seed/generators/catalog.py).
Balloon numbers 1..N are guaranteed to exist for every seeded part (the
catalog generator always assigns at least 10 characteristics per part,
numbered from 1), so this script's fixed subset of low balloon numbers is
valid against any real seeded catalog regardless of that generator's random
characteristic count/tolerances -- the *values* below are independently
drawn, not read from a live database, so don't expect them to match a
specific seed run's numbers exactly.
"""
from __future__ import annotations

import csv
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

import numpy as np
from openpyxl import Workbook

# seed/generators/catalog.py imports `app.models` (backend/ isn't an
# installed package) -- mirror seed/db.py's sys.path setup so this script
# can import the catalog constants without needing a database connection.
_BACKEND_ROOT = Path(__file__).resolve().parents[2] / "backend"
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from seed.generators.catalog import CHARACTERISTIC_TYPES, FAMILIES, TOLERANCE_RANGES  # noqa: E402

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "sample_files"
# Independent of the DB seed's default_seed (scenarios.yaml): these files
# ship as static repo assets regenerated by this script, not produced by a
# live `python -m seed` run.
SAMPLE_FILE_SEED = 20260711
CHARACTERISTICS_PER_PART = 6  # <= the minimum characteristic count (10) every seeded part has
SAMPLES_PER_FILE = 5


@dataclass(frozen=True)
class SampleCharacteristic:
    balloon: str
    column: str
    nominal: float
    upper_tol: float


def _characteristics_for_part(rng: np.random.Generator) -> list[SampleCharacteristic]:
    characteristics = []
    for i in range(CHARACTERISTICS_PER_PART):
        char_type = CHARACTERISTIC_TYPES[i % len(CHARACTERISTIC_TYPES)]
        nominal_min, nominal_max, tol_min, tol_max = TOLERANCE_RANGES[char_type]
        nominal = round(float(rng.uniform(nominal_min, nominal_max)), 3) if nominal_max > 0 else 0.0
        tolerance = round(float(rng.uniform(tol_min, tol_max)), 3)
        balloon = str(i + 1)
        characteristics.append(
            SampleCharacteristic(balloon=balloon, column=f"COL_{balloon}", nominal=nominal, upper_tol=tolerance)
        )
    return characteristics


def _rows_for_part(
    rng: np.random.Generator,
    part_code: str,
    machine_code: str,
    characteristics: list[SampleCharacteristic],
    start_at: datetime,
    force_nok_row: bool,
) -> list[dict]:
    rows = []
    for sample_index in range(1, SAMPLES_PER_FILE + 1):
        measured_at = start_at + timedelta(hours=sample_index)
        row: dict = {
            "part_number": part_code,
            "batch_lot": f"BATCH-{measured_at:%Y%m%d}-NEW",
            "run_at": measured_at.isoformat(),
            "machine_code": machine_code,
            "operator_identifier": "DEMO-OPERATOR",
            "sample_sequence": sample_index,
        }
        for char_index, characteristic in enumerate(characteristics):
            # The last sample's first characteristic gets pushed clearly out
            # of tolerance so importing this file live produces a real
            # compliance alert, not just more in-spec noise.
            is_forced_nok = force_nok_row and sample_index == SAMPLES_PER_FILE and char_index == 0
            if is_forced_nok:
                deviation = characteristic.upper_tol * 1.6
            else:
                noise_std = characteristic.upper_tol * 0.2
                deviation = float(rng.normal(0.0, noise_std))
            row[characteristic.column] = round(characteristic.nominal + deviation, 6)
        rows.append(row)
    return rows


def _write_csv(path: Path, rows: list[dict]) -> None:
    fieldnames = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_xlsx(path: Path, sheets: dict[str, list[dict]]) -> None:
    workbook = Workbook()
    workbook.remove(workbook.active)
    for sheet_name, rows in sheets.items():
        sheet = workbook.create_sheet(title=sheet_name)
        fieldnames = list(rows[0].keys())
        sheet.append(fieldnames)
        for row in rows:
            sheet.append([row[field] for field in fieldnames])
    workbook.save(path)


def generate_sample_files(output_dir: Path = OUTPUT_DIR) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(SAMPLE_FILE_SEED)
    now = datetime.now(timezone.utc)

    # (part_code, machine_code, force one clearly-NOK sample) -- part codes
    # come straight from seed/generators/catalog.py's FAMILIES so they match
    # whatever a real seed run creates.
    plan = [
        (FAMILIES[0][2][0][0], "CMM-01", True),  # MI-DEMO-1001: one NOK sample -> alert on import
        (FAMILIES[0][2][1][0], "CMM-01", False),  # MI-DEMO-1002: all-OK batch
        (FAMILIES[1][2][0][0], "CMM-02", False),  # MI-DEMO-1004: all-OK batch
    ]

    written: list[Path] = []
    xlsx_sheets: dict[str, list[dict]] = {}

    for index, (part_code, machine_code, force_nok_row) in enumerate(plan):
        characteristics = _characteristics_for_part(rng)
        start_at = now + timedelta(hours=1 + index)
        rows = _rows_for_part(rng, part_code, machine_code, characteristics, start_at, force_nok_row)

        csv_path = output_dir / f"{part_code.lower().replace('-', '_')}_import_batch.csv"
        _write_csv(csv_path, rows)
        written.append(csv_path)

        xlsx_sheets[part_code] = rows

    xlsx_path = output_dir / "mi_demo_import_batch.xlsx"
    _write_xlsx(xlsx_path, xlsx_sheets)
    written.append(xlsx_path)

    return written


if __name__ == "__main__":
    for generated_path in generate_sample_files():
        print(f"Wrote {generated_path}")
